### PR TITLE
Add Platforms x86 x64 any cpu

### PR DESCRIPTION
**Pull request by Furtif**

### CODE REVIEW

**Comment by msx752** [comment]
is it done ?  i will merge or you can also

**Comment by Furtif** [comment]
@msx752 Yes, I saw it, but I leave it to you so observe if I did shit lol, the stool happens ... Otherwise ok this is tested in 3 configurations build ok, you can do it

**Comment by Furtif** [comment]
missing assets!!!

**Comment by Furtif** [comment]
canot run this.. app closed

**Comment by msx752** [comment]
@Furtif https://mega.nz/#!aEBGmZ7b!EwSmPmyJxcO0PYUYzuk5Suy3s8j-V99yvz0oMTtEmnI download this file and put in debug folder

**Comment by Furtif** [comment]
@msx752  ok ok Has to be placed in source...

**Pull request merged**
